apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dspace-ingress
spec:
  tls:
    - hosts:
        - &host ok-dspace.dyn.cloud.e-infra.cz
      secretName: ok-dspace-dyn-cloud-e-infra-cz-tls # wish I could concat
  rules:
    - host: *host
      http:
        paths:
          - path: /server
            pathType: Prefix
            backend:
              service:
                name: dspace-backend-service
                port:
                  number: 8080

          - path: /
            pathType: Prefix
            backend:
              service:
                name: dspace-angular-service
                port:
                  number: 4000
