apiVersion: v1
kind: Service
metadata:
  name: dspace-angular-service
spec:
  selector:
    app: dspace-angular
  ports:
    - name: http
      protocol: TCP
      port: 4000
      targetPort: 4000
  type: ClusterIP
