apiVersion: v1
kind: Service
metadata:
  name: dspace-backend-service
spec:
  selector:
    app: dspace-backend
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
