apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dspace-ingress
  annotations:
    # Letsencrypt TLS
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
    # Enable proxy buffering off for SSE/long responses if needed
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    # Additional timeout settings for DSpace
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "75"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "6000"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "6000"
    # Backend protocol
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    # Rate limiting
    nginx.ingress.kubernetes.io/limit-rps: "500"
    nginx.ingress.kubernetes.io/limit-connections: "50"
    # Web Application Firewall (ModSecurity)
    nginx.ingress.kubernetes.io/enable-modsecurity: "true"
    nginx.ingress.kubernetes.io/enable-owasp-core-rules: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10g"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - hello-clarin-dspace.dyn.cloud.e-infra.cz
      secretName: hello-clarin-dspace-dyn-cloud-e-infra-cz-tls
  rules:
    - host: hello-clarin-dspace.dyn.cloud.e-infra.cz
      http:
        paths:
          - path: /server
            pathType: Prefix
            backend:
              service:
                name: dspace-backend-service
                port:
                  number: 8080

          - path: /
            pathType: Prefix
            backend:
              service:
                name: dspace-angular-service
                port:
                  number: 4000
