apiVersion: v1
kind: Secret
metadata:
  name: dspace-postgres-superuser
type: kubernetes.io/basic-auth
stringData:
  # Change password before deploying to production!
  username: dspace
  password: PASSWORD
